### PR TITLE
Update rules_python and add missing BUILD files

### PR DESCRIPTION
**Pull request by limdor**
Fixes: https://github.com/limdor/p2p-lending/issues/9

### CODE REVIEW

**Comment by aquintanas** [comment]
I returned to draft status because when I tried to build `bazel build ::/main` the following error rises:

```
no such package 'data/mintos': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/aquintanas/BSC/git/xavi/data/mintos and referenced by '//:main'
ERROR: Analysis of target '//:main' failed; build aborted: Analysis failed
INFO: Elapsed time: 60.468s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 127 targets configured)
    Fetching @local_config_cc; Restarting.
`
``

**Review by aquintanas — COMMENTED** [review]
Read the previous message because an error is still raised.

**Comment by aquintanas** [comment]
A file is missing:

```
INFO: Analyzed target //:main (33 packages loaded, 2284 targets configured).
INFO: Found 1 target...
ERROR: /Users/aquintanas/BSC/git/p2p-lending/BUILD:4:10: Middleman _middlemen/main-runfiles failed: missing input file '//:__init__.py'
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/aquintanas/BSC/git/p2p-lending/BUILD:4:10 Middleman _middlemen/main-runfiles failed: 1 input file(s) do not exist
INFO: Elapsed time: 92.298s, Critical Path: 2.16s
```

**Comment by limdor** [comment]
Moving forward. We are getting closer ;-)

**Comment by limdor** [comment]
```
Report containing only latest data
***********************************
**** Collecting available data ****
***********************************
Traceback (most recent call last):
  File "/home/limdor/.cache/bazel/_bazel_limdor/9e689524375e44be2878637953213343/execroot/__main__/bazel-out/k8-fastbuild/bin/main.runfiles/__main__/main.py", line 10, in <module>
    p2p.report(show_past_investments)
  File "/home/limdor/Bazel/p2p-lending/p2p.py", line 87, in report
    investment_files = collect_investment_data(DATA_DIRECTORY)
  File "/home/limdor/Bazel/p2p-lending/p2p.py", line 65, in collect_investment_data
    investment_platforms = [entry.name for entry in os.scandir(data_directory) if entry.is_dir()]
FileNotFoundError: [Errno 2] No such file or directory: './data'
```
Now what you should see if you do not have files is this. Probably we should improve the error message in a follow up.

**Comment by aquintanas** [comment]
It builds:

```
aquintanas@Adrias-Air p2p-lending % bazel build //:main  
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:main (33 packages loaded, 2284 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 51.731s, Critical Path: 2.08s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
`````

It works: 

````
aquintanas@Adrias-Air p2p-lending % bazel  run //:main
INFO: Analyzed target //:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.529s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Report containing only latest data
````

Hence, it is done!

**Review by aquintanas — APPROVED** [review]
Just a comment,

In the BUILD files of the data folders, 

```
filegroup(
    name = "iuvo",
    srcs = glob(["MyInvestments-*.xlsx"]),
    visibility = ["//visibility:public"],
)
```

Why not define the files directly as: `*.xlsx`? From my point of view, our code should control the name of the files instead of Bazel.

**Comment by limdor** [comment]
> Just a comment,
> 
> In the BUILD files of the data folders,
> 
> ```
> filegroup(
>     name = "iuvo",
>     srcs = glob(["MyInvestments-*.xlsx"]),
>     visibility = ["//visibility:public"],
> )
> ```
> 
> Why not define the files directly as: `*.xlsx`? From my point of view, our code should control the name of the files instead of Bazel.

Yes, that could be an option

**Pull request merged**
